#!/bin/sh
# DEPENDENCIES:
#   - notify-send
#
# RELEASED UNDER GPLv3
# REPO: https://github.com/TruncatedDinosour/youusebtw

main() {
    while true; do
        sleep "$(/bin/cat /etc/yub || echo '10m')"
        distro="$(/bin/grep -io '^NAME=.*$' < /etc/os-release | /bin/awk '{split($0,name,"="); print tolower(name[2]) }' | sed 's/"//g')"
        /usr/bin/notify-send "A reminder that you indeed, use ${distro} btw."
    done
}

main "$@"

